### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by mmatloka** [addthis/metrics-reporter-config#31]
Hi,
Can you release to maven central new version with zabbix and influxdb support? :)

**Comment by mmatloka** [comment]
@yuesong :)

**Comment by yuesong** [comment]
I'll try to do a release sometime next week!

**Comment by mmatloka** [comment]
Thanks in advance!

**Comment by yuesong** [comment]
@mmatloka new release is on its way to maven central.

**Comment by mmatloka** [comment]
thanks!
